//
// Created by KoenDR06 on 6/19/24.
//

#ifndef WHATSAPPSTATS_CALCULATETIMEDIFFERENCE_H
#define WHATSAPPSTATS_CALCULATETIMEDIFFERENCE_H

void calculateTimeDifference();

#endif //WHATSAPPSTATS_CALCULATETIMEDIFFERENCE_H
