//
// Created by KoenDR06 on 6/19/24.
//

#ifndef WHATSAPPSTATS_CALCULATETIMEOFDAY_H
#define WHATSAPPSTATS_CALCULATETIMEOFDAY_H

void calculateTimeOfDay();

#endif //WHATSAPPSTATS_CALCULATETIMEOFDAY_H
